image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 1NNB8szb8hFKc6BKbQhB6LjS2qrdINF/R8snmqeerzWCn+gTjKxdeGTAoypRc6Ne

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name QRGenerator --icon icon.png --product-name QRGenerator --product-version "0.0.1" --copyright "Copyright (c) 2023 Roberto-Parra Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a QRGenerator-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: QRGenerator-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf QRGenerator-macos.tar.gz -C dist QRGenerator.app

  artifacts:
  - path: QRGenerator-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf QRGenerator-linux.tar.gz -C dist QRGenerator

  artifacts:
  - path: QRGenerator-linux.tar.gz